#!/usr/bin/env python3
"""Ask for the full pipeline config and write docker-compose.generated.yml."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
INPUT_DIR = ROOT / "data" / "input"
OUTPUT_FILE = ROOT / "docker-compose.generated.yml"
PIPELINES = ("flink", "spark")


def ask(prompt: str, default: str | None = None) -> str:
    suffix = f" [{default}]" if default is not None else ""
    value = input(f"{prompt}{suffix}: ").strip()
    if value:
        return value
    if default is not None:
        return default
    print("A value is required.", file=sys.stderr)
    return ask(prompt, default)


def ask_int(prompt: str, minimum: int = 1) -> int:
    raw = ask(prompt)
    try:
        value = int(raw)
    except ValueError:
        print("Enter a whole number.", file=sys.stderr)
        return ask_int(prompt, minimum)
    if value < minimum:
        print(f"Enter a number >= {minimum}.", file=sys.stderr)
        return ask_int(prompt, minimum)
    return value


def ask_float(prompt: str) -> float:
    raw = ask(prompt)
    try:
        value = float(raw)
    except ValueError:
        print("Enter a number.", file=sys.stderr)
        return ask_float(prompt)
    if value <= 0:
        print("Enter a number greater than 0.", file=sys.stderr)
        return ask_float(prompt)
    return value


def list_csvs() -> list[str]:
    files = sorted(path.name for path in INPUT_DIR.glob("*.csv"))
    if not files:
        print(f"No CSV files found in {INPUT_DIR}", file=sys.stderr)
        sys.exit(1)
    print("\nAvailable CSVs in data/input/:")
    for index, name in enumerate(files, start=1):
        print(f"  {index}) {name}")
    return files


def ask_csv(client_index: int, files: list[str]) -> str:
    default = files[(client_index - 1) % len(files)]
    raw = ask(f"CSV for client {client_index}", default)
    if raw.isdigit():
        choice = int(raw)
        if 1 <= choice <= len(files):
            return files[choice - 1]
        print("Pick a number from the list or a file name.", file=sys.stderr)
        return ask_csv(client_index, files)
    if raw in files:
        return raw
    print(f"Unknown file '{raw}'. Use a name from the list.", file=sys.stderr)
    return ask_csv(client_index, files)


def ask_pipeline() -> str:
    raw = ask("Server pipeline [flink/spark]").lower()
    if raw in PIPELINES:
        return raw
    print("Choose flink or spark.", file=sys.stderr)
    return ask_pipeline()


def render_compose(
    client_count: int,
    rows_per_second: float,
    csvs: list[str],
    pipeline: str,
) -> str:
    processor_dockerfile = f"server/{pipeline}/Dockerfile"
    processor_service = pipeline
    lines = [
        "# Generated by scripts/generate-compose.py. Do not edit by hand.",
        "services:",
        "  kafka:",
        "    image: apache/kafka:3.9.1",
        "    hostname: kafka",
        "    profiles: [server]",
        "    environment:",
        "      KAFKA_NODE_ID: 1",
        "      KAFKA_PROCESS_ROLES: broker,controller",
        "      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093",
        "      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092",
        "      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT",
        "      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093",
        "      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER",
        "      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT",
        "      CLUSTER_ID: 4L6g3nShT-eMCtK--X86sw",
        "      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1",
        "      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1",
        "      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1",
        "      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0",
        "      KAFKA_AUTO_CREATE_TOPICS_ENABLE: \"true\"",
        "    healthcheck:",
        "      test: [\"CMD-SHELL\", \"/opt/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list\"]",
        "      interval: 5s",
        "      timeout: 10s",
        "      retries: 20",
        "  kafka-init:",
        "    image: apache/kafka:3.9.1",
        "    profiles: [server]",
        "    depends_on:",
        "      kafka:",
        "        condition: service_healthy",
        "    restart: \"no\"",
        "    entrypoint: [\"/opt/kafka/bin/kafka-topics.sh\"]",
        "    command:",
        "      - --bootstrap-server",
        "      - kafka:9092",
        "      - --create",
        "      - --if-not-exists",
        "      - --topic",
        "      - events",
        "      - --partitions",
        "      - \"2\"",
        "      - --replication-factor",
        "      - \"1\"",
        f"  {processor_service}:",
        "    profiles: [server]",
        "    build:",
        "      context: .",
        f"      dockerfile: {processor_dockerfile}",
        "    environment:",
        "      KAFKA_BOOTSTRAP: kafka:9092",
        "      KAFKA_TOPIC: events",
        "      OUTPUT_DIR: /data/output",
        "    volumes:",
        "      - ./data/output:/data/output",
        "    depends_on:",
        "      kafka:",
        "        condition: service_healthy",
        "      kafka-init:",
        "        condition: service_completed_successfully",
    ]

    for index, csv_name in enumerate(csvs, start=1):
        lines.extend(
            [
                f"  client-{index}:",
                "    profiles: [client]",
                "    build:",
                "      context: .",
                "      dockerfile: client/Dockerfile",
                "    environment:",
                f"      INPUT_PATH: /data/input/{csv_name}",
                f"      ROWS_PER_SECOND: \"{rows_per_second:g}\"",
                "      KAFKA_BOOTSTRAP: kafka:9092",
                "      KAFKA_TOPIC: events",
                f"      CLIENT_ID: client-{index}",
                "    volumes:",
                "      - ./data/input:/data/input:ro",
            ]
        )

    lines.append("")
    return "\n".join(lines)


def main() -> None:
    client_count = ask_int("How many clients?")
    rows_per_second = ask_float("How many rows per second?")
    files = list_csvs()
    csvs = [ask_csv(index, files) for index in range(1, client_count + 1)]
    pipeline = ask_pipeline()

    OUTPUT_FILE.write_text(
        render_compose(client_count, rows_per_second, csvs, pipeline),
        encoding="utf-8",
    )
    print(f"\nWrote {OUTPUT_FILE.name}")
    print("\nTerminal 1:  make server")
    print("Terminal 2:  make client")


if __name__ == "__main__":
    main()
